name: Example deploys

on:
  schedule: 
    - cron: 42 */1 * * * 
  workflow_dispatch:

permissions:
  deployments: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@main
        name: Create GitHub deployment
        with:
          token: "${{ github.token }}"
          environment-url: https://example.com
          initial-status: "success"
          environment: production
