name: Example deploys

on:
  schedule: 
    - cron: 42 */1 * * * 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@main
        name: Create GitHub deployment
        with:
          token: "${{ github.token }}"
          target_url: https://example.com
          initial_status: "success"
          environment: production
